CREATE EXTERNAL TABLE USERLOGS (
	DAY string,
	TICKTIME string/*,
	"USER_ID" string,
	"H_VALUE" string*/
)
ROW FORMAT DELIMITED
FIELDS TERMINATED BY ',' 
STORED AS TEXTFILE
LOCATION '/userlogs/data/';
